### ISSUE TITLE
Issue with requests version

### ISSUE THREAD

**Issue by sepulworld** [lemonlatte/docker-moztrap#1]
Hi! Thanks for sharing this Docker setup for moztraps!

I switched over to using the 'master' branch of moztraps by updating the checkout here:
https://github.com/lemonlatte/docker-moztrap/blob/master/Dockerfile#L13
to 'master'.

However, it looks like the older python 'requests' version used by moztraps isn't able to install. Curious if you have run into this error yet and have a workaround.

```
Collecting requests==0.14.1 (from -r /moztrap/requirements/pure.txt (line 23))
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/requests.egg-info
    writing pip-egg-info/requests.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/requests.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/requests.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/requests.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ep_Hmk/requests/setup.py", line 67, in <module>
        'Programming Language :: Python :: 3.1',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 279, in run
        self.find_sources()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 294, in find_sources
        mm.run()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 525, in run
        self.add_defaults()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 561, in add_defaults
        sdist.add_defaults(self)
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/sdist.py", line 133, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python2.7/distutils/cmd.py", line 311, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python2.7/distutils/dist.py", line 845, in get_command_obj
        klass = self.get_command_class(command)
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 490, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
        return self.resolve()
      File "/moztrap/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/moztrap/.venv/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 12, in <module>
        from six.moves import map, filter, filterfalse
    ImportError: cannot import name filterfalse

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ep_Hmk/requests/
The command '/bin/sh -c ./with_venv.sh ./bin/install-reqs' returned a non-zero code: 1
```

**Comment by fozcode** [comment]
I have the same error installing `requests` for a different package and it appears to be related to a recent change in `setuptools`. Downgrading setuptools like this fixes the problem for me:
`pip install 'setuptools>=33,<34'`

**Comment by sepulworld** [comment]
Thank you! Works for me as well.

**Comment by sebastiantoro** [comment]
Worked for me too!

**Comment by ghost** [comment]
Thanks a lot

**Comment by WhitleyStriber** [comment]
Thank you @fozcode

**Comment by iamwithnail** [comment]
Lovely, appreciate that!
